run black formatting during ci and pre-commit

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -24,9 +24,8 @@ echo "## begin #################################################################
 # For now it's just lint...
 echo "## lint ########################################################################"
 script/lint
-# TODO:
-#echo "## formatting ##################################################################"
-#script/format --check || (echo "Formatting check failed, run ./script/format" && exit 1)
+echo "## formatting ##################################################################"
+script/format --check || (echo "Formatting check failed, run ./script/format" && exit 1)
 echo "## tests/coverage ##############################################################"
 script/coverage
 echo "## complete ####################################################################"
